// Real per-category product page content, keyed by Shopify's own templateSuffix (products.template_suffix,
// backfilled from a live re-pull -- see scripts/shopify/backfill-template-suffix.ts). Every string below was
// read verbatim from the real theme export (data/exports/theme/templates/product.*.json, walking each
// section's/block's real nested block tree), never reworded or guessed -- including the real source typo
// ("smcykena"), the inconsistent accordion-heading casing across templates ("Specifikationer" vs
// "specifikationer", "Smyckesvård" vs "smyckesvård" vs "Vård" vs "VÅrd"), and the FAQ's real answer that
// literally says "Stripe Payments" (not "Shopify Payments") -- confirmed genuine raw extracted text, not
// something this migration introduced. Same static-but-real-content pattern as lib/pages-content.ts.
//
// erbjudande-vaskor's intro paragraph is left exactly as extracted (byte-identical to the unrelated
// default-template copy, which itself is byte-identical to armband's near-copy) per explicit instruction:
// this is a confirmed pre-existing content bug in the real Shopify theme with no correct original text
// recoverable anywhere (checked all 32 products' descriptionHtml, their metafields, and
// config/settings_data.json -- nothing found). A replacement has been proposed separately and is pending
// approval; do not edit this file to "fix" it without that approval.

export type AccordionRow = { heading: string; body: string };

export type ProductTemplateContent = {
  introParagraph: string | null;
  trustLines: string[] | null;
  uspBlock: { heading: string; body: string }[] | null;
  faq: { question: string; answer: string }[] | null;
  // The first row always holds the product's own real descriptionHtml (dynamic, not static) --
  // descriptionHeading gives that row's real per-template heading text/casing. Further rows are
  // additional static category copy (care instructions, design philosophy), in real order.
  descriptionHeading: string;
  accordionRows: AccordionRow[];
  sizeGuideHref: string | null;
  offerMessage: { heading: string; body: string } | null;
  // Real theme: blocks/product-inventory.liquid, placed on 7/9 templates (absent on skal/default).
  // Drives the "I lager" / "{count} kvar" / "Slut i lager" messaging -- see product-detail.tsx.
  showInventoryStatus: boolean;
  // Real theme: _product-media-gallery block's media_presentation setting. Only armband/vaskor are
  // "carousel" (swipeable at every breakpoint); every other template is "grid" (a static stacked
  // grid on desktop that becomes the same swipeable carousel below the 1024px breakpoint).
  galleryLayout: "carousel" | "grid";
};

const JEWELRY_TRUST_LINES = ["14 dagars öppet köp", "Fri frakt & Fria byten", "Betala säkert med Klarna", "Vattentåligt & nickelfritt"];
const VASKOR_TRUST_LINES = ["14 dagars öppet köp", "Fri frakt", "Betala säkert med Klarna"];

const JEWELRY_USP_BLOCK = [
  { heading: "Vattentåliga smycken", body: "Alla våra smycken är nickelfria och tål vatten samt behåller sin glans över tid." },
  { heading: "Fria byten", body: "Enkelt och smidigt byte inom 14 dagar." },
  {
    heading: "Premium kvalitét",
    body: "Alla våra smycken är tillverkade i antingen rostfritt stål eller titan stål, och guld smcykena är pläterade med 18K guld för en exklusiv finish och långvarig glans.",
  },
  { heading: "Garanti", body: "Vi erbjuder 60 dagars garanti för en trygg och säker köpupplevelse." },
];

const JEWELRY_FAQ = [
  { question: "Vilken returpolicy gäller?", answer: "Vi har 14 dagars öppet köp, no questions asked." },
  { question: "Har ni garanti på era smycken?", answer: "Ja, alla våra smycken kommer med 60 dagars garanti för en trygg och säker köpupplevelse." },
  {
    question: "Hur lång är leveranstiden?",
    answer:
      "Leveranstiden är 5–10 arbetsdagar. Vi arbetar med internationella leverantörer och lager, vilket gör att vi kan erbjuda noggrant utvalda smycken av hög kvalitet till ett mer tillgängligt pris. Alla beställningar skickas spårbart direkt till dig.",
  },
  {
    question: "Hur mycket kostar frakten?",
    answer: "Vi erbjuder alltid fri frakt på alla beställningar, oavsett ordervärde. Din beställning skickas spårbart direkt hem till dig utan extra kostnad.",
  },
  {
    question: "Vilka betalningsmetoder erbjuder ni?",
    answer: "Vi erbjuder säkra betalningar via Klarna, kortbetalning och Apple/Google Pay. Alla betalningar hanteras tryggt genom Stripe Payments för en säker och smidig köpupplevelse.",
  },
];

const JEWELRY_CARE_ROW: AccordionRow = {
  heading: "Smyckesvård",
  body: "Rengör dina smycken genom att använda en mjuk och torr bomullstrasa. Gnugga försiktigt ytan. Använd inte något polermedel eller liknande. Dina smycken mår som bäst av att förvaras i ett smyckeskrin för att undvika att de repas eller oxiderar.",
};

export const PRODUCT_TEMPLATES: Record<string, ProductTemplateContent> = {
  armband: {
    introParagraph: "Armband som behåller sin glans och håller stilen längre. Vi gör ikonisk design tillgänglig för alla genom slitstarka premiummaterial.",
    trustLines: JEWELRY_TRUST_LINES,
    uspBlock: JEWELRY_USP_BLOCK,
    faq: JEWELRY_FAQ,
    descriptionHeading: "Specifikationer",
    accordionRows: [
      JEWELRY_CARE_ROW,
      {
        heading: "Design",
        body: "Inspirerad av världens mest ikoniska smycken – skapad för att hålla. Vi gör de mest eftertraktade designerna tillgängliga för alla, utan att tumma på kvaliteten. Med fokus på felfri finish, rätt tyngd och slitstarka material får du den ultimata lyxkänslan till ett smart pris.",
      },
    ],
    sizeGuideHref: null,
    offerMessage: null,
    showInventoryStatus: true,
    galleryLayout: "carousel",
  },

  halsband: {
    introParagraph: "Halsband som lyfter din stil och tål att bäras varje dag. Vi gör eftertraktade trender tillgängliga för alla genom en kompromisslös kvalitet.",
    trustLines: JEWELRY_TRUST_LINES,
    uspBlock: JEWELRY_USP_BLOCK,
    faq: JEWELRY_FAQ,
    descriptionHeading: "Specifikationer",
    accordionRows: [
      JEWELRY_CARE_ROW,
      {
        heading: "Design",
        body: "Inspirerad av världens mest kända halsband. Vi gör de mest populära smyckena tillgängliga för alla, utan att fuska med kvaliteten. Med fokus på rätt tyngd, en fin yta och slitstarka material får du den rätta lyxkänslan som lyfter varje outfit – till ett rimligt pris.",
      },
    ],
    sizeGuideHref: null,
    offerMessage: null,
    showInventoryStatus: true,
    galleryLayout: "grid",
  },

  orhangen: {
    introParagraph: "Örhängen som ger rätt lyxkänsla och sitter perfekt hela dagen. Vi gör trendiga modeller tillgängliga för alla genom slitstarka material som behåller sin fina yta.",
    trustLines: JEWELRY_TRUST_LINES,
    uspBlock: JEWELRY_USP_BLOCK,
    faq: JEWELRY_FAQ,
    descriptionHeading: "specifikationer",
    accordionRows: [
      { ...JEWELRY_CARE_ROW, heading: "smyckesvård" },
      {
        heading: "Design",
        body: "Ikoniska örhängen som sätter stilen direkt. Vi erbjuder de mest populära modellerna och gör lyxig design tillgänglig för alla, utan att fuska med kvaliteten. Med fokus på låg vikt, en fin yta och starka material får du örhängen som både känns bekväma och ser fantastiska ut.",
      },
    ],
    sizeGuideHref: null,
    offerMessage: null,
    showInventoryStatus: true,
    galleryLayout: "grid",
  },

  ringar: {
    introParagraph: "Ringar som tål att bäras varje dag och behåller sin fina yta. Vi gör populära modeller tillgängliga för alla genom slitstarka material som faktiskt håller.",
    trustLines: JEWELRY_TRUST_LINES,
    uspBlock: JEWELRY_USP_BLOCK,
    faq: JEWELRY_FAQ,
    descriptionHeading: "Specifikationer",
    accordionRows: [
      { ...JEWELRY_CARE_ROW, heading: "smyckesvård" },
      {
        heading: "Design",
        body: "Ikoniska ringar i modern tappning. Vi erbjuder de mest populära modellerna tillgängliga för alla, utan att fuska med kvaliteten. Med fokus på rätt tyngd, en fin yta och slitstarka material får du den rätta lyxkänslan på fingrarna – till ett smart pris.",
      },
    ],
    sizeGuideHref: "/pages/ringstorlek",
    offerMessage: null,
    showInventoryStatus: true,
    galleryLayout: "grid",
  },

  vaskor: {
    introParagraph: "Väskor som sätter stilen och tål att användas varje dag. Vi erbjuder trendiga modeller i tåliga material",
    trustLines: VASKOR_TRUST_LINES,
    uspBlock: null,
    faq: JEWELRY_FAQ,
    descriptionHeading: "Specifikationer",
    accordionRows: [
      {
        heading: "VÅrd",
        body: "Ta hand om din väska genom att torka av den med en mjuk, fuktig trasa vid behov. Undvik att överfylla väskan så att den håller formen, och skydda den mot kraftigt regn och fukt. Förvara den torrt när den inte används.",
      },
      {
        heading: "Design",
        body: "Ikoniska väskor som sätter stilen direkt. Vi erbjuder eftertraktade modeller och gör lyxig design tillgänglig för alla, utan att kompromissa med kvaliteten. Med fokus på fina detaljer, slitstarka material och en perfekt passform får du en väska som både rymmer din vardag och ser fantastisk ut.",
      },
    ],
    sizeGuideHref: null,
    offerMessage: null,
    showInventoryStatus: true,
    galleryLayout: "carousel",
  },

  "erbjudande-vaskor": {
    // Real, confirmed-stale intro text -- see file header. Left unchanged pending separate approval.
    introParagraph:
      "Vi erbjuder armband som behåller sin glans och håller stilen längre. Våra smycken löser dilemmat mellan lyx och prislapp genom ikonisk design och slitstarka premiummaterial.",
    trustLines: null,
    uspBlock: null,
    faq: null,
    descriptionHeading: "Specifikationer",
    accordionRows: [
      {
        heading: "Vård",
        body: "Ta hand om din väska genom att torka av den med en mjuk, fuktig trasa vid behov. Undvik att överfylla väskan så att den håller formen, och skydda den mot kraftigt regn och fukt. Förvara den torrt när den inte används.",
      },
    ],
    sizeGuideHref: null,
    offerMessage: {
      heading: "Få en valfri plånbok på köpet!",
      body: "Lägg väskan och en valfri plånbok från kategorin Tillbehör i kundvagnen – plånboken blir gratis.",
    },
    showInventoryStatus: true,
    galleryLayout: "grid",
  },

  planbok: {
    introParagraph: "Plånböcker med stilren design och en känsla av lyx.",
    trustLines: null,
    uspBlock: null,
    faq: null,
    descriptionHeading: "Specifikationer",
    accordionRows: [], // real template: only the dynamic description row -- nothing static to add
    sizeGuideHref: null,
    offerMessage: null,
    showInventoryStatus: true,
    galleryLayout: "grid",
  },

  // "RH skal" -- one-off bespoke template; the real theme's own marketing copy existed only here
  // (not in the product's own Shopify description), which is why it got its own template.
  skal: {
    introParagraph:
      "Förstklassigt skydd i en sofistikerad förpackning. Vi utmanar idén om att lyxiga mobiltillbehör måste kosta skjortan, och erbjuder stilrena skal gjorda för att hålla sig fräscha dag efter dag.",
    trustLines: null,
    uspBlock: null,
    faq: null,
    descriptionHeading: "Specifikationer",
    accordionRows: [
      {
        heading: "Beskrivning",
        body:
          "<h3><strong>Den ultimata skönhetsaccessoaren – Det smarta silikonskalet</strong></h3><p>Ge din telefon och dina läppar en lyxig uppgradering med det mest omtalade tillbehöret just nu. Detta skal löser det klassiska vardagsdilemmat och kombinerar ett stöttåligt skydd med en smart, integrerad hållare för din läppglans. Nu har du alltid din favoritprodukt nära till hands för en snabb touch-up.</p><p>Skalet är tillverkat i ett silkeslen, greppvänligt premium-silikon med en mjuk, matt finish som känns fantastisk att hålla i. Den upphöjda designen runt kameran och skärmen ger ett optimalt skydd mot stötar och repor.</p><p>Det perfekta mötet mellan ikonisk estetik, slitstarka material och smart funktion.</p>",
      },
    ],
    sizeGuideHref: null,
    offerMessage: null,
    showInventoryStatus: false,
    galleryLayout: "grid",
  },
};

export function getProductTemplateContent(templateSuffix: string | null): ProductTemplateContent | null {
  if (!templateSuffix) return null;
  return PRODUCT_TEMPLATES[templateSuffix] ?? null;
}
